###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring_SR'
  SESSION: 'Restormer_4x'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 100
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 3e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
#  TRAIN_DIR_LQ: '/home/misak/Desktop/REDS/lmdb2/train_240_blur_bicubic_X4.lmdb' # path to LQ training data
#  TRAIN_DIR_GT: '/home/misak/Desktop/REDS/lmdb2/train_240_sharp.lmdb' # path to GT training data
#  VAL_DIR_LQ: '/home/misak/Desktop/REDS/lmdb/val_30_blur_bicubic_X4.lmdb'    # path to LQ validation data
#  VAL_DIR_GT: '/home/misak/Desktop/REDS/lmdb/val_30_sharp.lmdb'    # path to GT validation data
  TRAIN_DIR: '/home/misak/Desktop/REDS/Train_Renamed'    # path to LQ, GT train data
  VAL_DIR: '/home/misak/Desktop/REDS/Val300'    # path to LQ, GT validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
